// Committed demo documents (generated by scripts/generate-demo-scenes.mjs with the real
// engine, so they are always valid SceneDocuments). Kept in a leaf module so the outer
// frame can type `scene` without pulling scene data or the engine into its chunk.
export type DemoSceneName = 'quick-start' | 'shapes-tour' | 'flowchart';
